---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    ansible.builtin.yum:
      update_cache: yes

  - name: install httpd package
    ansible.builtin.yum:
      name: httpd,php-fpm,php-cli,php-mysqlnd
      state: latest

  - name: install support for php
    ansible.builtin.yum:
      name: php 
      state: latest
